const {
  generarReporte,
} = require("./src/services/reportes/planeacionReportesEngine");
const Module = require("module");

// Mock de dependencias para evitar ERR_DLOPEN_FAILED
// Necesitamos que layoutService provea el layout real si es posible,
// o al menos que no explote.
// Pero ya vimos que falla al cargar sqlite o firebird.
// Intentaré un mock que lea el JSON si existe.

const originalRequire = Module.prototype.require;
Module.prototype.require = function (name) {
  if (
    name.includes("planeacionCuentasService") ||
    name.includes("saldosService") ||
    name.includes("firebird")
  ) {
    return {
      obtenerDatosPlaneacionResumen: () => Promise.resolve([]),
      MESES: [{ clave: "Enero", periodo: 1 }],
    };
  }
  return originalRequire.apply(this, arguments);
};

const engine = require("./src/services/reportes/planeacionReportesEngine");

async function debug() {
  try {
    // Si no podemos usar generarReporte por la DB, usaremos construirReporteResumen directamente
    const layoutPath = "PLANTILLAS 2026+/GUADALAJARA 2026/RESUMEN_layout.json";
    const layoutRaw = require("fs").readFileSync(layoutPath, "utf-8");
    const layoutJson = JSON.parse(layoutRaw);

    const definiciones = layoutJson.RESUMEN;
    const configAgrupacion = layoutJson.Operaciones;

    // Simular planeacionData con los valores del screenshot (aprox)
    // REAL ENE 2026
    const planeacionData = [
      {
        cuenta: "400000000000000000000",
        actualMonth: 92228.1,
        planMonth: 39950.58,
        prevMonth: 4563.21,
      }, // Membership Income?
      {
        cuenta: "702000000000000000000",
        actualMonth: 92228.1,
        planMonth: 39950.58,
        prevMonth: 4563.21,
      }, // Membership Expense
      {
        cuenta: "405000000000000000000",
        actualMonth: 412419.45,
        planMonth: 700000,
        prevMonth: 24047.83,
      }, // Events
      {
        cuenta: "701000000000000000000",
        actualMonth: 412419.45,
        planMonth: 700000,
        prevMonth: 24047.83,
      }, // Events Expense
      {
        cuenta: "502000000000000000000",
        actualMonth: 30085.95,
        planMonth: 36000,
        prevMonth: 0,
      }, // Committees
      {
        cuenta: "601000000000000000000",
        actualMonth: 32050,
        planMonth: 41265,
        prevMonth: 39300,
      }, // Services
      {
        cuenta: "801000000000000000000",
        actualMonth: 102567.88,
        planMonth: 153853.71,
        prevMonth: 101689.86,
      }, // G&A
      {
        cuenta: "501000000000000000000",
        actualMonth: 599806.95,
        planMonth: 559332.32,
        prevMonth: 374295.29,
      }, // Nomina
      {
        cuenta: "903000000000000000000",
        actualMonth: 331103.03,
        planMonth: 360748.33,
        prevMonth: 299581.1,
      }, // Corp
      {
        cuenta: "903016000000000000000",
        actualMonth: 253199.8,
        planMonth: 253199.79,
        prevMonth: 226322.0,
      }, // Admin
    ];

    const opciones = {
      permitirFormulaSecciones: true,
      ordenManualTotal: true,
      modoFormulaEstricto: true,
      seccionesComoOperaciones: true,
      autoGeneratedAggregateRows: false,
    };

    const result = engine.construirReporteResumen(
      definiciones.filter((d) => d.CAPITULO === "GUADALAJARA"),
      configAgrupacion,
      "GUADALAJARA",
      planeacionData,
      opciones,
    );

    console.log("=== RESULTS DUMP ===");
    result.principals.forEach((p) => {
      console.log(`\nPrincipal: [${p.label}] ActualMonth: ${p.actualMonth}`);
      let sum = 0;
      p.children.forEach((c) => {
        console.log(`  - ${c.label}: ${c.totalActualMonth}`);
        sum += Number(c.totalActualMonth || 0);
      });
      console.log(`  SUM OF CHILDREN: ${sum}`);
    });

    console.log("\n=== LAYOUT DUMP (Principals) ===");
    result.layout
      .filter((l) => l.type === "principal")
      .forEach((l) => {
        console.log(`Principal: [${l.label}] Total: ${l.totals.actualMonth}`);
      });
  } catch (error) {
    console.error("Error during debug:", error);
  }
}

debug();
