const test = require("node:test");
const assert = require("node:assert/strict");
const path = require("path");
const fs = require("fs");
const Module = require("module");

// Mock de dependencias antes de cargar el engine
const originalRequire = Module.prototype.require;
Module.prototype.require = function (name) {
  if (
    name.includes("planeacionCuentasService") ||
    name.includes("saldosService") ||
    name.includes("layoutService") ||
    name.includes("firebird")
  ) {
    return {
      obtenerDatosPlaneacionResumen: () => Promise.resolve([]),
      MESES: [{ clave: "Enero", periodo: 1 }],
    };
  }
  return originalRequire.apply(this, arguments);
};

const engine = require("../src/services/reportes/planeacionReportesEngine");

async function debugRun() {
  const layoutPath = path.join(
    __dirname,
    "../PLANTILLAS 2026+/GUADALAJARA 2026/RESUMEN_layout.json",
  );
  const layoutRaw = fs.readFileSync(layoutPath, "utf-8");
  const layoutJson = JSON.parse(layoutRaw);

  const definiciones = layoutJson.RESUMEN.filter(
    (d) => d.CAPITULO === "GUADALAJARA",
  );
  const targetDef = definiciones.find(
    (d) => d.CUENTA === "400000000000000000000",
  ); // Membership Income
  if (targetDef) {
    targetDef.operacion_factor = -1; // Forzamos factor -1
  }

  const configAgrupacion = [
    {
      nombre: "Membership",
      tipo: "cuentas",
      expresion: "400000000000000000000",
      seccion: "INCOME",
      CAPITULO: "GUADALAJARA",
    },
  ];

  const planeacionData = [
    {
      cuenta: "400000000000000000000",
      actualMonth: 1000,
      planMonth: 0,
      prevMonth: 0,
    },
  ];

  const opciones = {
    permitirFormulaSecciones: true,
    ordenManualTotal: true,
    modoFormulaEstricto: true,
    seccionesComoOperaciones: true,
    autoGeneratedAggregateRows: false,
  };

  const result = engine.construirReporteResumen(
    definiciones,
    configAgrupacion,
    "GUADALAJARA",
    planeacionData,
    opciones,
  );

  const testOp = result.layout.find(
    (l) => l.label === "Membership" && l.type === "secundaria",
  );

  if (!testOp) {
    process.stdout.write(
      "❌ FAILURE: Membership operation not found in layout.\n",
    );
    process.exit(1);
  }

  process.stdout.write("\n=== FACTOR AWARE FORMULA TEST ===\n");
  process.stdout.write(`Account: 400... (Membership)\n`);
  process.stdout.write(`Account Raw Value: 1000\n`);
  process.stdout.write(`Account Factor in Def: -1\n`);
  process.stdout.write(`Formula Result: ${testOp.totals.actualMonth}\n`);

  if (testOp.totals.actualMonth === -1000) {
    process.stdout.write("✅ SUCCESS: Formula applied factor correctly.\n");
  } else {
    process.stdout.write(
      `❌ FAILURE: Formula result ${testOp.totals.actualMonth} did not match expected -1000.\n`,
    );
    process.exit(1);
  }
}

debugRun().catch((err) => {
  process.stdout.write(err.stack + "\n");
  process.exit(1);
});
